pull_request_title: 'chore: new Crowdin translation'
pull_request_labels:
  - translations
files:
  - source: content.json
    translation: '%original_file_name%_%two_letters_code%'
bundles:
  - 8
  - 12
