{\rtf1\ansi\ansicpg1252\cocoartf2708
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;\f1\froman\fcharset0 Times-Roman;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 pull_request_title: "chore: new Crowdin translation"
\f1\fs24 \

\f0\fs26 pull_request_labels:
\f1\fs24 \

\f0\fs26 \'a0\'a0- translations
\f1\fs24 \

\f0\fs26 files:
\f1\fs24 \

\f0\fs26 \'a0\'a0- source: /main/content.json
\f1\fs24 \

\f0\fs26 \'a0\'a0\'a0\'a0translation: /i18n/content_%locale_with_underscore%.json
\f1\fs24 \
}